// Seed data for books (frontend-only)
import type { Book } from "./types"

export const seedBooks = (): Book[] => [
  {
    id: "b-001",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    description: "Practical tips and timeless principles for becoming a more effective software developer.",
    categories: ["Technology", "Non-Fiction"],
    coverUrl: "/software-book-cover.png",
    totalCopies: 5,
    availableCopies: 3,
    isFree: false,
  },
  {
    id: "b-002",
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "Guidelines, best practices, and patterns for writing clean, maintainable code.",
    categories: ["Technology", "Non-Fiction"],
    coverUrl: "/clean-code-book-cover.png",
    totalCopies: 4,
    availableCopies: 0,
    isFree: false,
  },
  {
    id: "b-003",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description: "An accessible exploration of cosmology, black holes, and the nature of the universe.",
    categories: ["Science", "Non-Fiction", "History"],
    coverUrl: "/science-cosmology-book-cover.png",
    totalCopies: 6,
    availableCopies: 4,
    isFree: true,
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "b-004",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A classic American novel exploring wealth, love, and the American Dream.",
    categories: ["Fiction"],
    coverUrl: "/classic-novel-cover.png",
    totalCopies: 8,
    availableCopies: 2,
    isFree: false,
  },
  {
    id: "b-005",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "A sweeping narrative of human history, from hunter-gatherers to the modern era.",
    categories: ["History", "Non-Fiction", "Philosophy"],
    coverUrl: "/history-book-cover.png",
    totalCopies: 7,
    availableCopies: 5,
    isFree: false,
  },
  {
    id: "b-006",
    title: "You Don't Know JS Yet",
    author: "Kyle Simpson",
    description: "A deep dive into the mechanics and nature of JavaScript for serious learners.",
    categories: ["Technology", "Non-Fiction"],
    coverUrl: "/javascript-book-cover.png",
    totalCopies: 3,
    availableCopies: 1,
    isFree: true,
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "b-007",
    title: "The Marvelous Adventures",
    author: "Jane Doe",
    description: "A light-hearted comic adventure across fantastical lands and curious characters.",
    categories: ["Comics", "Fiction"],
    coverUrl: "/comic-book-cover.png",
    totalCopies: 10,
    availableCopies: 9,
    isFree: false,
  },
  {
    id: "b-008",
    title: "Meditations",
    author: "Marcus Aurelius",
    description: "Stoic reflections on virtue, resilience, and the nature of a good life.",
    categories: ["Philosophy", "Non-Fiction"],
    coverUrl: "/philosophy-book-cover.png",
    totalCopies: 5,
    availableCopies: 5,
    isFree: true,
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
]
